name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: build image and to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: johnathanalves
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: johnathanalves/argocd
          tags: ${{github.sha}}, latest